import Head from "next/head";
import { useRouter } from "next/router";
import styles from "@/styles/Home.module.css";
import { Button, Space } from "antd";

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Full-stack test task</h1>
        <Space wrap>
          <Button type="link" onClick={() => router.push('messages')}>Messages</Button>
          <Button type="link" onClick={() => router.push('numbers')}>Numbers</Button>
        </Space>
      </main>
    </>
  );
}
